version: "3"
services:
  starwars-database:
    image: mongo
    container_name: "starwars-database"
    ports:
      - 27017:27017
    restart: unless-stopped
  api:
    container_name: "starwars-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - starwars-database